#                                                                        #
# Routes configuration                                                   #
#                                                                        #
# This file contains the configuration for the MVC router.               #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the FLOW3 manual for possible configuration options.   #
#                                                                        #

##
# Fallback route

FLOW3_Fallback:
  uriPattern: ''
  controllerObjectNamePattern: 'F3::@package::MVC::Controller::@controllerController'
  defaults:
    @package:    FLOW3
    @controller: Default
    @action:     index

##
# Default route with just the package

FLOW3_DefaultWithPackage:
  uriPattern: '[@package]'
  defaults:
    @controller: Default
    @action:     index
    @format:     html

##
# Default route to map the first three URL segments to package, controller and action

FLOW3_Default:
  uriPattern: '[@package]/[@controller]/[@action]'
  defaults:
    @controller: Default
    @action:     index
    @format:     html

##
# Default route to map the first three URL segments to package, controller and action 
# including optional format-suffix

FLOW3_DefaultWithFormat:
  uriPattern: '[@package]/[@controller]/[@action].[@format]'
  defaults:
    @controller: Default
    @action:     index
    @format:     html

##
# Default route to map the first three URL segments to package, controller and action 
# including format and optional GET parameters

FLOW3_DefaultWithFormatAndParameters:
  uriPattern: '[@package]/[@controller]/[@action].[@format]?[parameters]'
  defaults:
    @controller: Default
    @action:     index
    @format:     html
