#                                                                        #
# Default subroutes configuration for the FLOW3 package                  #
#                                                                        #

# $Id$

##
# Default route to the FLOW3 Login Controller

--
  name: 'Login with action'
  uriPattern: '/login/{@action}'
  defaults:
    @package:    'FLOW3'
    @subpackage: 'Security'
    @controller: 'Login'

--
  name: 'Login'
  uriPattern: '/login'
  defaults:
    @package:    'FLOW3'
    @subpackage: 'Security'
    @controller: 'Login'
    @action:     'index'