#                                                                        #
# Configuration for the FLOW3 Framework                                  #
#                                                                        #
# This file contains additions to the base configuration for the FLOW3   #
# Framework when it runs in Development context.                         #
#                                                                        #
# Don't modify this file - instead put your own additions into the       #
# global Configuration directory and its sub directories.                #
#                                                                        #

TYPO3:

  FLOW3:

    configuration:
      compileConfigurationFiles: FALSE

    core:
      subRequestEnvironmentVariables:
        XDEBUG_CONFIG: 'idekey=FLOW3_SUBREQUEST remote_port=9001'

    error:
      exceptionHandler:
        className: 'TYPO3\FLOW3\Error\DebugExceptionHandler'
      errorHandler:
        exceptionalErrors: [%E_USER_ERROR%, %E_RECOVERABLE_ERROR%, %E_WARNING%, %E_NOTICE%, %E_USER_WARNING%, %E_USER_NOTICE%, %E_STRICT%]

    resource:
      publishing:
        detectPackageResourceChanges: TRUE

    log:
      systemLogger:
        backendOptions:
          logFileURL: %FLOW3_PATH_DATA%Logs/System_Development.log
          severityThreshold: %LOG_DEBUG%
      securityLogger:
        backendOptions:
          logFileURL: %FLOW3_PATH_DATA%Logs/Security_Development.log
          severityThreshold: %LOG_DEBUG%
      sqlLogger:
        backendOptions:
          logFileURL: %FLOW3_PATH_DATA%Logs/Query_Development.log
          severityThreshold: %LOG_DEBUG%
